/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/consolidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Consolidate */
        post: operations["admin_consolidate_api_admin_consolidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Forget */
        post: operations["admin_forget_api_admin_forget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reflect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Reflect */
        post: operations["admin_reflect_api_admin_reflect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Restart
         * @description Restart the server by re-executing the process in place.
         *
         *     Reloads on-disk code without losing the stdio MCP pipe, so connected
         *     clients re-handshake transparently. ``SYNARA_*`` is re-read from the
         *     current process environment, which ``execv`` preserves unchanged — so
         *     editing a ``SYNARA_*`` value takes effect only after restarting the
         *     MCP client (which re-spawns this process), not via this route.
         *     Disruptive: every
         *     connected session (and this dashboard) briefly drops while the new
         *     image comes up. Guarded by the dashboard bearer token like every
         *     other ``/api`` route. The re-exec is scheduled a beat later so this
         *     reply reaches the client first.
         */
        post: operations["admin_restart_api_admin_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sr Graph */
        get: operations["sr_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memories */
        get: operations["list_memories_api_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Detail */
        get: operations["memory_detail_api_memories__episode_id__get"];
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_memories__episode_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Params
         * @description Effective MemoryConfig snapshot.
         *
         *     Read-only: ``MemoryConfig`` is frozen; live mutation would require
         *     rebuilding SR/plasticity and is deliberately out of scope here.
         */
        get: operations["params_api_params_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/semantic/{semantic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semantic Detail */
        get: operations["semantic_detail_api_semantic__semantic_id__get"];
        put?: never;
        post?: never;
        /** Delete Semantic */
        delete: operations["delete_semantic_api_semantic__semantic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tool-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tool Metrics
         * @description Snapshot the per-tool call count, last-called time, and p50/p95 latency.
         *
         *     Tool list is server-authoritative: every tool declared on the
         *     collector at server start appears here even if it hasn't been
         *     called yet (``count=0``, latency fields ``null``), so the dashboard
         *     can render the full surface on the first poll.
         */
        get: operations["tool_metrics_api_tool_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConsolidateBody */
        ConsolidateBody: {
            /** Min Cluster Size */
            min_cluster_size?: number | null;
            /** N Clusters */
            n_clusters?: number | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** ConsolidateResult */
        ConsolidateResult: {
            /** Schemas */
            schemas: {
                [key: string]: unknown;
            }[];
            /** Schemas Formed */
            schemas_formed: number;
        };
        /** ConsolidationEdge */
        ConsolidationEdge: {
            /** Dst */
            dst: string;
            /** Src */
            src: number;
        };
        /** DeleteResult */
        DeleteResult: {
            /** Count */
            count: number;
            /** Deleted Ids */
            deleted_ids: number[];
        };
        /** EpisodicGraphNode */
        EpisodicGraphNode: {
            /** Consolidated Into */
            consolidated_into: number;
            /** Created At */
            created_at: number;
            /** Embedding */
            embedding: number[] | null;
            /** Group Id */
            group_id: number;
            /** Id */
            id: number;
            /** Is Focus */
            is_focus: boolean;
            /** Key */
            key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "episodic";
            /** Label */
            label: string;
            /** Last Accessed */
            last_accessed: number;
            /** Preview */
            preview: string;
            /** Retrieval Count */
            retrieval_count: number;
            /** Salience */
            salience: number;
            /** Segment Count */
            segment_count: number;
            /** Session Id */
            session_id: string | null;
        };
        /** ForgetBody */
        ForgetBody: {
            /** Decay Tau Seconds */
            decay_tau_seconds?: number | null;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /**
             * Max Scan
             * @default 1000
             */
            max_scan: number;
            /**
             * Strength Floor
             * @default 0.05
             */
            strength_floor: number;
        };
        /** ForgetResult */
        ForgetResult: {
            /** Candidate Ids */
            candidate_ids: number[];
            /** Cold Schema Candidate Ids */
            cold_schema_candidate_ids: number[];
            /** Dry Run */
            dry_run: boolean;
            /** Removed */
            removed: number;
            /** Scanned */
            scanned: number;
            /** Schemas Removed */
            schemas_removed: number;
            /** Schemas Scanned */
            schemas_scanned: number;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Consolidation Edges */
            consolidation_edges: components["schemas"]["ConsolidationEdge"][];
            /** Episode Count */
            episode_count: number;
            /** Focus */
            focus: number | null;
            /** Nodes */
            nodes: (components["schemas"]["EpisodicGraphNode"] | components["schemas"]["SemanticGraphNode"])[];
            /** Omega */
            omega: number;
            /** Plasticity Edges */
            plasticity_edges: components["schemas"]["PlasticityEdge"][];
            /** Semantics Truncated */
            semantics_truncated: boolean;
            /** Sr Edges */
            sr_edges: components["schemas"]["SrEdge"][];
            /** Truncated */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Db Path */
            db_path: string;
            /**
             * Embedding Backend
             * @enum {string}
             */
            embedding_backend: "local" | "remote";
            /** Embedding Model */
            embedding_model: string;
            /** Mcp Client */
            mcp_client: string;
            /** Status */
            status: string;
            /** Transport */
            transport: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /**
         * MemoryBrowse
         * @description ``GET /memories`` without ``q`` — paginated raw listing.
         */
        MemoryBrowse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["MemoryListItem"][];
            /** Kind */
            kind: string;
            /** Offset */
            offset: number;
        };
        /** MemoryDetailResponse */
        MemoryDetailResponse: {
            /** Group Id */
            group_id: number;
            /** Id */
            id: number;
            /** Plasticity Edges */
            plasticity_edges: components["schemas"]["PlasticityEdgeDetail"][];
            /** Segments */
            segments: {
                [key: string]: unknown;
            }[];
            /** Sr Transitions */
            sr_transitions: components["schemas"]["SrTransition"][];
            /** Sr Transitions In */
            sr_transitions_in: components["schemas"]["SrTransitionIn"][];
        };
        /** MemoryListItem */
        MemoryListItem: {
            /** Content */
            content: string;
            /** Id */
            id: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * MemorySearch
         * @description ``GET /memories?q=`` — hybrid recall + substring search.
         *
         *     Hit items carry open keys (distance, score, source, metadata,
         *     substring_offset) so they stay ``dict[str, Any]`` — modelling them
         *     strictly would drop fields the UI relies on.
         */
        MemorySearch: {
            /** Count */
            count: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Kind */
            kind: string;
            /** Query */
            query: string;
            /**
             * Recall Mode
             * @enum {string}
             */
            recall_mode: "semantic" | "substring" | "hybrid" | "empty";
        };
        /** PlasticityEdge */
        PlasticityEdge: {
            /** Bonus */
            bonus: number;
            /** Dst */
            dst: number;
            /** Hits */
            hits: number;
            /** Is Habit */
            is_habit: boolean;
            /** Src */
            src: number;
            /** Strength */
            strength: number;
            /** Weight */
            weight: number;
        };
        /** PlasticityEdgeDetail */
        PlasticityEdgeDetail: {
            /** Bonus */
            bonus: number;
            /** Dst */
            dst: number;
            /** Hits */
            hits: number;
            /** Src */
            src: number;
            /** Weight */
            weight: number;
        };
        /** ReflectBody */
        ReflectBody: {
            /**
             * K
             * @default 5
             */
            k: number;
            /** Query */
            query?: string | null;
            /** Session Id */
            session_id: string;
        };
        /**
         * RestartResult
         * @description ``POST /admin/restart`` — the server re-execs itself in place.
         */
        RestartResult: {
            /** Detail */
            detail: string;
            /** Status */
            status: string;
        };
        /** SemanticDetailResponse */
        SemanticDetailResponse: {
            /** Confidence */
            confidence: number;
            /** Content */
            content: string;
            /** Created At */
            created_at: number;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Source Episode Ids */
            source_episode_ids: number[];
            /** Tags */
            tags: string[];
            /** Updated At */
            updated_at: number;
            /** User Asserted */
            user_asserted: boolean;
        };
        /** SemanticGraphNode */
        SemanticGraphNode: {
            /** Confidence */
            confidence: number;
            /** Embedding */
            embedding: number[] | null;
            /** Id */
            id: number;
            /** Key */
            key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "semantic";
            /** Label */
            label: string;
            /** Preview */
            preview: string;
            /** Source Count */
            source_count: number;
            /** User Asserted */
            user_asserted: boolean;
        };
        /** SrEdge */
        SrEdge: {
            /** Dst */
            dst: number;
            /** Hits */
            hits: number;
            /** M */
            m: number;
            /** Src */
            src: number;
        };
        /** SrTransition */
        SrTransition: {
            /** Count */
            count: number;
            /** Dst */
            dst: number;
        };
        /** SrTransitionIn */
        SrTransitionIn: {
            /** Count */
            count: number;
            /** Src */
            src: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Consolidate Epoch */
            consolidate_epoch: number;
            /** Episodic Count */
            episodic_count: number;
            /** Schema Candidate Count */
            schema_candidate_count: number;
            /** Semantic Count */
            semantic_count: number;
        } & {
            [key: string]: unknown;
        };
        /** ToolMetricRow */
        ToolMetricRow: {
            /** Count */
            count: number;
            /** Error Count */
            error_count: number;
            /** Headline */
            headline: string;
            /** Last Called At */
            last_called_at: number | null;
            /** Last Duration Seconds */
            last_duration_seconds: number | null;
            /** Name */
            name: string;
            /** P50 Ms */
            p50_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
        };
        /** ToolMetricsResponse */
        ToolMetricsResponse: {
            /** Tools */
            tools: components["schemas"]["ToolMetricRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_consolidate_api_admin_consolidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsolidateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsolidateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_forget_api_admin_forget_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_reflect_api_admin_reflect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_restart_api_admin_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResult"];
                };
            };
        };
    };
    sr_graph_api_graph_get: {
        parameters: {
            query?: {
                focus?: number | null;
                depth?: number;
                max_nodes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_memories_api_memories_get: {
        parameters: {
            query?: {
                kind?: "episodic" | "semantic";
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryBrowse"] | components["schemas"]["MemorySearch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_detail_api_memories__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_api_memories__episode_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    params_api_params_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    semantic_detail_api_semantic__semantic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semantic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_semantic_api_semantic__semantic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semantic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    tool_metrics_api_tool_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMetricsResponse"];
                };
            };
        };
    };
}
